Idmapping max ids
ebi-uniprot/uniprot-rest-api pull request #226
Opened 2021-12-17 09:45 UTC by ahmadshadab

2022-01-06 15:25 UTC, eddturner requested changes

2022-01-06 16:10 UTC, ahmadshadab commented on idmapping-rest/src/main/java/org/uniprot/api/idmapping/model/PredefinedIdMappingStatus.java
> +    FACET_WARNING(20, "Filters are not supported for mapping results with IDs more than "),
I just made it up. :-)

2022-01-06 16:13 UTC, ahmadshadab commented on idmapping-rest/src/main/java/org/uniprot/api/idmapping/service/BasicIdService.java
> +            throw new InvalidRequestException(ENRICHMENT_WARNING.getMessage() + this.maxIdMappingToIdsCountEnriched);
Yes, thats right. I have added this code prevent user from constructing url

2022-01-06 16:14 UTC, ahmadshadab commented on common-rest/src/main/java/org/uniprot/api/common/repository/search/WarningPair.java
> +public class WarningPair {
Changed it to ProbelmPair

2022-01-10 09:24 UTC, eddturner approved these changes

2022-01-10 10:24 UTC, merged